Support react-navigation 1.0.0-beta.28+ (#185)
* Fixes  FAIL  Tests/StoriesTest.js
  ● Test suite failed to run

    /node_modules/@storybook/react-native/dist/preview/components/OnDeviceUI/menu_open.png:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){�PNG
                                                                                             ^

    SyntaxError: Invalid or unexpected token

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:303:17)
      at Object.<anonymous> (node_modules/@storybook/react-native/dist/preview/components/OnDeviceUI/index.js:51:21)
      at Object.<anonymous> (node_modules/@storybook/react-native/dist/preview/index.js:47:19)

* Support react-navigation 1.0.0-beta.28+.
Bump react-native version to 0.52.2.

* Linting.